Add caliban to benchmarks
tailcallhq/graphql-benchmarks pull request #5
Opened 2023-11-09 10:55 UTC by kyri-petrou

Hey guys, just wanted to add Caliban (from Scala) to the benchmarks.

Just wanted to highlight a couple of things:

1. The warmup that was previously being done didn't seem enough for JDK apps so I added a few more rounds. The JVM is still not fully warm after it but I think it's _good enough_.
2. The benchmarks in this PR are from a 2 CPU machine (in GH CodeSpace), which show TC ahead. Given that using such a low number of cores gives a fairly big disadvantage to JVM apps, I also run them with a 16-core machine, and these are RPS results:

![image](https://github.com/tailcallhq/graphql-benchmarks/assets/67301607/3aa0bced-cb8e-4cb9-ae8c-e31644dee17c)

Just as feedback, I think it might be good to add a range of machine cores to the benchmarks just to highlight where different languages / libraries might have some advantage over others

2023-11-10 03:01 UTC, tusharmath requested changes

2023-11-10 03:01 UTC, tusharmath commented on graphql/caliban/src/main/scala/Main.scala
> +    } yield Response(Status.Ok, contentTypeJson, Body.fromChunk(Chunk.fromArray(writeToArray(resp))))
```suggestion
    } yield Response(Status.Ok, contentTypeJson, Body.fromChunk(Chunk.fromArray(writeToArray(resp)))).withServerTime
```
Just to make sure we are spec compliant.

2023-11-10 12:18 UTC, tusharmath commented
Can you run the benchmark again and push the results.

2023-11-10 13:21 UTC, kyri-petrou commented
Eghh I think that even after adding the extra warmups, the server is nowhere near warm enough at lower CPU :(

First _recorded_ run (i.e., after warmups) at 4CPU:

```
Running 10s test @ http://localhost:8084/graphql
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   148.82ms  226.51ms   1.39s    91.87%
    Req/Sec   303.11    125.76   580.00     62.64%
  10799 requests in 10.05s, 55.43MB read
Requests/sec:   1074.99
Transfer/sec:      5.52MB
```

3rd one:
```
Running 10s test @ http://localhost:8084/graphql
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    28.59ms    9.23ms 117.71ms   75.91%
    Req/Sec     0.88k   179.45     1.32k    69.75%
  35124 requests in 10.02s, 180.28MB read
Requests/sec:   3506.39
Transfer/sec:     18.00MB
```

2023-11-14 06:59 UTC, tusharmath commented
@kyri-petrou How is it in comparison to others?

> Just as feedback, I think it might be good to add a range of machine cores to the benchmarks just to highlight where different languages / libraries might have some advantage over others

Can you open an issue for this? We can definitely run it on a series cpus.

2023-11-14 08:19 UTC, kyri-petrou commented
> @kyri-petrou How is it in comparison to others?

The netflix server seems to have the same issue. The Apollo / Go / Tailcall have the same performance across all 3 _measured_ runs.

> Can you open an issue for this? We can definitely run it on a series cpus.

Yeah can do. The other thing which might be good is to perhaps consider using GraalVM as the JDK. Our benchmarks in the Caliban repo which measure the internal performance only have a ~50-100% higher throughput running on GraalVM. I still don't know why our execution benefits _this much_ from GraalVM though.

2023-11-15 09:00 UTC, tusharmath commented
@kyri-petrou 
I think this PR still has the older results.  If that's the case, can you run again and update the PR please?

Our benchmarks are typically done on a 4core machine, which ideal for a production environment also. A layer like this should be scaled horizontally and not vertically to be cost-effective. So it's preferred to have 2-4 core machines in general.

We could use Graalvm. Feel free to make that change, I doubt the performance will change significantly.

2023-11-15 10:18 UTC, kyri-petrou commented
Hmm I'm not sure why tailcall is showing up as `null` though :/ let me try and rerun them

2023-11-15 10:27 UTC, kyri-petrou commented
OK seems to have worked now

2023-11-18 11:31 UTC, tusharmath approved these changes

2023-11-18 11:31 UTC, merged